import { Article, Source } from "../model/News";

export const MOCK_NEWS: Article[] = [
    {
        source: {
            id: null,
            name: "Kvraudio.com",
        },
        author: null,
        title: "FS: Audio Ease Altiverb 7 (in: Sell and Buy (+Spe...)",
        description: "By: grocery45 20 Apr 07:22 Hello folks. Offering Altiverb 7 for sale. iLok license transfer. https://bitify.com/auctions/download-software/audio-ease-altiverb-7-reverb-plugin-vst-aax-1818087 Bitify is a marketplace platform similar to eBay that supports Bitco…",
        url: "https://www.kvraudio.com/forum/viewtopic.php?t=523919",
        urlToImage: "http://static.kvraudio.com/i/b/kvraudio-300x300-grey-eeeeee.png",
        publishedAt: "2019-04-20T07:22:15Z",
        content: "AUTO-ADMIN:Non-MP3, WAV, OGG, SoundCloud, YouTube, Vimeo, Twitter and Facebook links in this post have been protected automatically. Once the member reaches 5 posts the links will function as normal.\r\nHello folks.Offering Altiverb 7 for sale. iLok license tra… [+468 chars]",
    },
    {
        source: {
            id: null,
            name: "Newsbtc.com",
        },
        author: "Martin Young",
        title: "Crypto Market Wrap: Unstoppable Binance Leading Markets Back to 2019 Highs",
        description: "Crypto markets approaching 2019 highs; Binance Coin unstoppable, BCH still climbing and Ravecoin flying. Market Wrap Crypto markets are marching slowly and steadily higher as another weekend unfolds. Total market capitalization is back over $180 billion again…",
        url: "https://www.newsbtc.com/2019/04/20/crypto-market-wrap-unstoppable-binance-leading-markets-back-to-2019-highs/",
        urlToImage: "https://www.newsbtc.com/wp-content/uploads/2018/07/Binance-Burn.jpg",
        publishedAt: "2019-04-20T07:00:09Z",
        content: "Crypto markets approaching 2019 highs; Binance Coin unstoppable, BCH still climbing and Ravecoin flying.\r\nCrypto markets are marching slowly and steadily higher as another weekend unfolds. Total market capitalization is back over $180 billion again as it appr… [+2832 chars]",
    },
    {
        source: {
            id: null,
            name: "Abovetopsecret.com",
        },
        author: "ucanthandlethetruth",
        title: "Need Bitcoin Knowledge - Mueller Report Bitcoin Doesnt Make Sense",
        description: "Need Bitcoin Knowledge - Mueller Report Bitcoin Doesn't Make Sense, page 1",
        url: "http://www.abovetopsecret.com/forum/thread1236870/pg1",
        urlToImage: "http://files.abovetopsecret.com/images/ats11.jpg",
        publishedAt: "2019-04-20T06:43:44Z",
        content: "CNNI have many questions: \r\nRussian operatives used cryptocurrency at almost every stage in their online efforts to interfere in the 2016 U.S. presidential election,\r\naccording to Special Counsel Robert Mueller's final report on his investigation. Systems use… [+3749 chars]",
    },
    {
        source: {
            id: null,
            name: "Hackernoon.com",
        },
        author: "Ted Shabecoff",
        title: "Predicting a Crypto Summer in 2021",
        description: "Since early 2018, the cryptocurrency markets have fallen precipitously. As with previous crashes, many have claimed that the markets are…",
        url: "https://hackernoon.com/predicting-a-crypto-summer-in-2021-1b1266806d23",
        urlToImage: "https://cdn-images-1.medium.com/max/1200/1*hEZDgg6q2EiQQ4Gp-bnT4A.jpeg",
        publishedAt: "2019-04-20T05:11:03Z",
        content: "What might trigger the next bull run? Firstly, a Bitcoin block reward halving is anticipated for May of 2020 and may trigger bullish market sentiment or a Crypto Spring. In 2016, the market responded to a Bitcoin halving by triggering a small uptick in the pr… [+3585 chars]",
    },
    {
        source: {
            id: null,
            name: "Indiegogo.com",
        },
        author: "Matthew Gerard",
        title: "Fri Apr 19 '19 Announcement from My Campaign Title",
        description: "Help me build a Bitcoin Casino website and app. I have a few thousand plus Connections in the gaming and blockchain Industry and have years of experience I will be hosting servers in CURACAO. I have a very good developer that can work quick and cheap licensin…",
        url: "https://www.indiegogo.com/projects/--23029?c=activity",
        urlToImage: null,
        publishedAt: "2019-04-20T05:10:15Z",
        content: null,
    },
    {
        source: {
            id: null,
            name: "Dailyfintech.com",
        },
        author: "Bernard Lunn",
        title: "Blockchain IPO: who will be first & when will it happen?",
        description: "TLDR. The first IPO by a Blockchain venture will signal that the next cryptocurrency bull market is in good shape. One question is which Blockchain venture will be the the first to IPO. Candidates include Binance, Coinbase, Silvergate & TZero. Looking at the …",
        url: "https://dailyfintech.com/2019/04/20/blockchain-ipo-who-will-be-first-when-will-it-happen/",
        urlToImage: "https://fintech4us.files.wordpress.com/2019/04/ipo-sto.001.jpeg",
        publishedAt: "2019-04-20T05:00:33Z",
        content: "TLDR. The first IPO by a Blockchain venture will signal that the next cryptocurrency bull market is in good shape. One question is which Blockchain venture will be the the first to IPO. Candidates include Binance, Coinbase, Silvergate &amp; TZero. Looking at … [+7275 chars]",
    },
    {
        source: {
            id: null,
            name: "Yahoo.com",
        },
        author: null,
        title: "What's missing? The clues to Barr's 1,000 Mueller report redactions",
        description: "Nearly 40% of the 448 pages have parts blacked out but that content – including remarks by Trump – is not a total mysteryThe attorney general, William Barr, made redactions under four categories: harm to ongoing matters; grand jury evidence; investigative tec…",
        url: "https://news.yahoo.com/apos-missing-clues-barr-apos-050016150.html",
        urlToImage: "https://s.yimg.com/uu/api/res/1.2/0iUQ6Bmj2o7uCKUeJqJalw--~B/aD0zMDA7dz01MDA7c209MTthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en-GB/the_guardian_765/6a32a91084e574e5b0cf933f97a17c73",
        publishedAt: "2019-04-20T05:00:16Z",
        content: "The Mueller report contains tantalising details of Trump campaign dealings with Russia and of the presidents possible attempts to obstruct justice. But much of it is blacked out. Nearly 40% of the pages in the document contain at least one redaction, totallin… [+7361 chars]",
    },
    {
        source: {
            id: null,
            name: "Newsbtc.com",
        },
        author: "Aayush Jindal",
        title: "Bitcoin Price Watch: BTC Primed For Lift-off To $5,500",
        description: "Bitcoin price remained well supported above the $5,200 and $5,160 levels against the US Dollar. The price is slowly grinding higher and it may well climb above the $5,350 level. There is a major ascending channel in place with support at $5,210 on the hourly …",
        url: "https://www.newsbtc.com/2019/04/20/bitcoin-price-btc-to-5500/",
        urlToImage: "https://www.newsbtc.com/wp-content/uploads/2018/08/techanalysis-btc6-bullish.jpg",
        publishedAt: "2019-04-20T04:08:55Z",
        content: "Bitcoin price remained well supported above the $5,200 and $5,160 levels against the US Dollar.\r\nThe price is slowly grinding higher and it may well climb above the $5,350 level.\r\nThere is a major ascending channel in place with support at $5,210 on the hourl… [+2304 chars]",
    },
    {
        source: {
            id: null,
            name: "Yahoo.com",
        },
        author: null,
        title: "Bitcoin Cash – ABC, Litecoin and Ripple Daily Analysis – 20/04/19",
        description: "It’s a mixed start to the day for the majors. A move through key levels would be needed to avoid a sell-off later in the day.",
        url: "https://finance.yahoo.com/news/bitcoin-cash-abc-litecoin-ripple-031226531.html",
        urlToImage: "https://s.yimg.com/uu/api/res/1.2/X8fmF7XjVVXW9CBIXwrYVA--~B/aD00MjA7dz02MzA7c209MTthcHBpZD15dGFjaHlvbg--/http://media.zenfs.com/en-US/homerun/fx_empire_176/9df49d2fd4a1fe0f4af5a15dd1639ef1",
        publishedAt: "2019-04-20T03:12:26Z",
        content: "Bitcoin Cash ABC rose by 0.2% on Friday. Partially reversing a 1.15% fall from Thursday, Bitcoin Cash ABC ended the day at $306.58.\r\nA particularly bearish start to the day saw Bitcoin Cash ABC tumble to an intraday low $291.91 before finding support.\r\nThe re… [+4240 chars]",
    },
    {
        source: {
            id: null,
            name: "Zerohedge.com",
        },
        author: "Tyler Durden",
        title: "Libertarian 'Seasteaders' Face Execution In Thailand For 'Violating National Sovereignty'",
        description: "Despite its location just outside of Thailand's territorial waters, leaving it outside the reach of the country's laws according to international maritime law, the world's second \"seastead\" was raided by Thai police earlier this week as the country's military…",
        url: "https://www.zerohedge.com/news/2019-04-19/libertarian-seasteaders-facing-execution-thailand-charges-violating-national",
        urlToImage: "https://zh-prod-1cc738ca-7d3b-4a72-b792-20bd8d8fa069.storage.googleapis.com/s3fs-public/styles/max_650x650/public/2019-04/Screen%20Shot%202019-04-19%20at%2011.59.04%20AM.png?itok=yxMG84AU",
        publishedAt: "2019-04-20T03:10:00Z",
        content: "Despite its location just outside  of Thailand's territorial waters, leaving it outside the reach of the country's laws according to international maritime law, the world's second \"seastead\" was raided by Thai police earlier this week as the country's militar… [+3427 chars]",
    },
];

export const MOCK_SOURCES: Source[] = [
    {
        id: "abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us",
    },
    {
        id: "abc-news-au",
        name: "ABC News (AU)",
        description: "Australia's most trusted source of local, national and world news. Comprehensive, independent, in-depth analysis, the latest business, sport, weather and more.",
        url: "http://www.abc.net.au/news",
        category: "general",
        language: "en",
        country: "au",
    },
    {
        id: "aftenposten",
        name: "Aftenposten",
        description: "Norges ledende nettavis med alltid oppdaterte nyheter innenfor innenriks, utenriks, sport og kultur.",
        url: "https://www.aftenposten.no",
        category: "general",
        language: "no",
        country: "no",
    },
    {
        id: "al-jazeera-english",
        name: "Al Jazeera English",
        description: "News, analysis from the Middle East and worldwide, multimedia and interactives, opinions, documentaries, podcasts, long reads and broadcast schedule.",
        url: "http://www.aljazeera.com",
        category: "general",
        language: "en",
        country: "us",
    },
    {
        id: "ansa",
        name: "ANSA.it",
        description: "Agenzia ANSA: ultime notizie, foto, video e approfondimenti su: cronaca, politica, economia, regioni, mondo, sport, calcio, cultura e tecnologia.",
        url: "http://www.ansa.it",
        category: "general",
        language: "it",
        country: "it",
    },
    {
        id: "argaam",
        name: "Argaam",
        description: "ارقام موقع متخصص في متابعة سوق الأسهم السعودي تداول - تاسي - مع تغطيه معمقة لشركات واسعار ومنتجات البتروكيماويات , تقارير مالية الاكتتابات الجديده ",
        url: "http://www.argaam.com",
        category: "business",
        language: "ar",
        country: "sa",
    },
    {
        id: "ars-technica",
        name: "Ars Technica",
        description: "The PC enthusiast's resource. Power users and the tools they love, without computing religion.",
        url: "http://arstechnica.com",
        category: "technology",
        language: "en",
        country: "us",
    },
];
